# Generated by Django 3.1.2 on 2021-04-21 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_products_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='catagory',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='store.catagory'),
        ),
        migrations.AddField(
            model_name='products',
            name='desc',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='img',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
