# Generated by Django 3.1.2 on 2021-04-22 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210422_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.catagory'),
        ),
    ]
