# Generated by Django 3.1.2 on 2021-04-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210422_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phno',
            field=models.BigIntegerField(unique=True),
        ),
    ]
