# Generated by Django 3.1.2 on 2021-08-15 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20210813_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(default=models.CharField(default='', max_length=100), max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
