# Generated by Django 3.1.2 on 2021-08-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20210816_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
