# Generated by Django 3.1.2 on 2021-08-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20210816_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='no_of_visits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
