# Generated by Django 3.1.2 on 2021-08-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_products_no_of_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='home_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='phno',
            field=models.IntegerField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='postal_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='shipping_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='zip_code',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
