# Generated by Django 3.1.2 on 2021-08-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20210817_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zip_code',
            field=models.IntegerField(default=0),
        ),
    ]
