# Generated by Django 3.1.2 on 2021-08-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20210817_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phno',
            field=models.BigIntegerField(default=0, max_length=15),
        ),
    ]
