# Generated by Django 3.1.2 on 2021-08-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20210818_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phno',
            field=models.BigIntegerField(default=0),
        ),
    ]
