# Generated by Django 3.1.2 on 2021-08-21 09:27

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_auto_20210820_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.fields.related.ManyToManyField, to='store.products'),
        ),
    ]
