# Generated by Django 3.1.2 on 2021-08-21 09:29

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_auto_20210821_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.fields.related.OneToOneField, to='store.products'),
        ),
    ]
