# Generated by Django 3.1.2 on 2021-08-26 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_products_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
