# Generated by Django 3.1.2 on 2021-08-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_remove_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name_additional',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phno_additional',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
