# Generated by Django 3.1.2 on 2021-08-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_auto_20210826_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='completed',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('paid', 'Paid'), ('packaged', 'Packaged'), ('shipped', 'Shipped'), ('completed', 'Completed')], default='created', max_length=20),
        ),
    ]
