# Generated by Django 3.1.2 on 2021-08-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_auto_20210826_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='confirm_password',
            field=models.CharField(max_length=200),
        ),
    ]
